Captures the jar name when any Exception occurs
...in ClassFileVisitor.processJarFile(), in the same style as is done
for IOException in the current source.

This handles cases like getting:

  java.lang.SecurityException: Invalid signature file digest for Manifest main attribute

from some signed jar.  The change will inject an IOException
encapsulating the original Exception, so a message like the following
will show up in stack traces (in addition to the above original cause):

  java.io.IOException:  exception while processing jar /path/to/the-offending.jar: Invalid signature file digest for Manifest main attributes